{% set version = '1.15.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-microeco
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/microeco_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/microeco/microeco_{{ version }}.tar.gz
  sha256: 427e540e671ad24cf6fa9365672bb2de40859a45c6f7cf37001053d09c71e917

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-rcolorbrewer
    - r-ape
    - r-data.table
    - r-dplyr
    - r-ggplot2 >=3.5.0
    - r-igraph >=2.0.0
    - r-lifecycle
    - r-magrittr
    - r-reshape2
    - r-rlang
    - r-scales
    - r-tibble
    - r-vegan
  run:
    - r-base
    - r-r6
    - r-rcolorbrewer
    - r-ape
    - r-data.table
    - r-dplyr
    - r-ggplot2 >=3.5.0
    - r-igraph >=2.0.0
    - r-lifecycle
    - r-magrittr
    - r-reshape2
    - r-rlang
    - r-scales
    - r-tibble
    - r-vegan

test:
  commands:
    - $R -e "library('microeco')"           # [not win]
    - "\"%R%\" -e \"library('microeco')\""  # [win]

about:
  home: https://github.com/ChiLiubio/microeco
  license: GPL-3
  summary: A series of statistical and plotting approaches in microbial community ecology based
    on the R6 class. The classes are designed for data preprocessing, taxa abundance
    plotting, alpha diversity analysis, beta diversity analysis, differential abundance
    test, null model analysis, network analysis, machine learning, environmental data
    analysis and functional analysis.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - LafontRapnouilTristan

# Package: microeco
# Type: Package
# Title: Microbial Community Ecology Data Analysis
# Version: 1.15.0
# Authors@R: c(person("Chi", "Liu", role = c("aut", "cre"), email = "liuchi0426@126.com"), person("Felipe", "R. P. Mansoldo", role = "ctb", email = "mansoldo@micro.ufrj.br"), person("Minjie", "Yao", role = "ctb", email = "yaomj@fafu.edu.cn"), person("Xiangzhen", "Li", role = "ctb", email = "lixz@cib.ac.cn") )
# Author: Chi Liu [aut, cre], Felipe R. P. Mansoldo [ctb], Minjie Yao [ctb], Xiangzhen Li [ctb]
# Maintainer: Chi Liu <liuchi0426@126.com>
# Description: A series of statistical and plotting approaches in microbial community ecology based on the R6 class. The classes are designed for data preprocessing, taxa abundance plotting, alpha diversity analysis, beta diversity analysis, differential abundance test, null model analysis, network analysis, machine learning, environmental data analysis and functional analysis.
# URL: https://github.com/ChiLiubio/microeco
# Depends: R (>= 3.5.0)
# Imports: R6, stats, ape, vegan, rlang, data.table, magrittr, dplyr, tibble, scales, grid, ggplot2 (>= 3.5.0), RColorBrewer, reshape2, igraph (>= 2.0.0), lifecycle
# Suggests: GUniFrac, MASS, ggpubr, randomForest, ggdendro, ggrepel, agricolae, gridExtra, picante, pheatmap, rgexf, mice, GGally
# License: GPL-3
# LazyData: true
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2025-05-18 05:19:14 UTC; Chi
# Repository: CRAN
# Date/Publication: 2025-05-18 11:10:02 UTC
# RoxygenNote: 7.3.2
